# Generated by Django 4.2 on 2023-12-30 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Myprofile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='お名前')),
                ('content', models.TextField(max_length=140, verbose_name='内容')),
            ],
        ),
    ]
